sonar.projectKey=oca-core-statusforge
sonar.projectName=oca-core-statusforge
sonar.projectVersion=1.0.0

# diisi dengan file/folder yang ingin discan jika lebih dari 1 maka gunakan "," sebagai pemisah
sonar.sources=./

# diisi dengan extensi yang ingin discan jika lebih dari 1 maka gunakan "," sebagai pemisah
sonar.inclusions=libs/config.js
sonar.exclusions=
#enable code coverage report
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.dynamicAnalysis=reuseReports
